
# ##########################################################
# Package

[package]

authors = [
	"Matt Wilson <matthew@synesis.com.au>",
]
categories = [
	"command-line-interface",
]
description = "Minimal ANSI terminal colour codes (for Rust)"
documentation = "https://docs.rs/woad"
edition = "2021"
exclude = [
	".cargo",
	".cursor",
	".github",
	".vimrc",
	".vscode",
	"scripts",
	"target",
]
homepage = "https://github.com/synesissoftware/woad.Rust"
keywords = [
	"ansi",
	"colour",
	"sgr",
	"terminal",
	"tty",
]
license = "BSD-3-Clause"
name = "woad"
readme = "README.md"
repository = "https://github.com/synesissoftware/woad.Rust"
rust-version = "1.74"
version = "0.0.1"


# ##########################################################
# Targets

[lib]
name = "woad"
path = "src/lib.rs"


# ##########################################################
# Features

[features]

default = [
]


# General features:
#
# - "_NEVER_TO_BE_ENABLED" - this is a placeholder feature and must NEVER be specified;
# - "null-feature" - a feature that has no effect (and, thus, is useful for simplifying driver scripts);

_NEVER_TO_BE_ENABLED = []
null-feature = []


# Crate-specific features:
#


# ##########################################################
# Dependencies

[build-dependencies]

[dependencies]

[dev-dependencies]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
